version: "3"
services: 
  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    ports:
      - "8086:8086"        
    env_file:
      - 'influxdb.env'
    volumes:
      - "influxdb-data:/var/lib/influxdb"

  grafana:
    image: grafana/grafana-oss:8.5.5
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'grafana.env'
    user: "0"
    volumes:
      - "grafana-data:/var/lib/grafana"
      - "./grafana-plugins:/var/lib/grafana/plugins"
  
  node-red:
    image: nodered/node-red:2.2.2
    container_name: node-red
    ports:
      - "1880:1880"
      - "1883:1883"
    volumes:
      - "node-red-data:/data"

  node:
    image: "node:16"
    container_name: nodejs
    user: "node"
    working_dir: /nodeapp/
    environment:
      - NODE_ENV=production
    volumes:
      - "./nodeapp/:/nodeapp/"
    ports:
      - "8081:8081"
    expose:
      - "8081"
    command: "npm start"

volumes:
  influxdb-data:
  grafana-data:        
  node-red-data:
  nodejs-data:
